language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: fathomless-wave-89304
  api_key:
    secure: b0CgWyrAICEFv4C9k4/cjpJEo6RfOBEfmDmpapML4C6qN0OgR+G3MXrYCepxPgCOCwXiHPu+DSi3p1Oka1OV2zvQIpE/mXKwPbB72h5PI4KCN2uWGvo0thrR0v/oY652I7+kYnfIEjJ1egM7GN99Tcuuy/kLEK2j2vx63Vvtbr42wj54u47fYAOc1pSpkEdNTCDTjgjdzkkXZJ0quEn9Sc0u63ocetC7Dim2NJxR34p9tOfZIW50F0x+ocqyz9jdPuG2I4ZNO8C8EnhdbFeukglCYuFoi4UZ4VWancjDs/12KWAxzLbCzBX5XuZHfsOY+oORlby4xz19E0WRIVmPqIuGJPuzxiMMR8WHRFPKkFIqAL264aswQULm2TU+xpN/pLZM0biPK6KFEwcPWm7GqN+6sCiHUXacpB4qnNTvvnZ9yIjd41ktBsHzOxu6uDYxKos7n0yLHFbn+MFVV0XmvBR0cK8Mg7/IMpxqOlnNv60Fc6ou8PPX/nysJG8PVZI9RlF7ScsDvmrZGfsmeiK6bhI2fwfWtzrjmz3ybSnWzdDHwzd2C1OKLTpMbVrNmDlHwPVZcOJ6iJTj+sTZMpl9f3p3wWPHTl7YX2G1oGmIU3yXZq68v5OcS3GZxKBDfLGnGiHrOavfIpZ7P2IjCIXSgvO5pIHqSQzSXBoLgsWjh2M=
